version: "3.8"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      minio:
        condition: service_healthy
    environment:
      GIN_MODE: release

      # External Postgres (NocoDB)
      DBHOST: ${dbhost}
      DBNAME: ${dbname}
      DBUSERNAME: ${dbusername}
      DBPASS: ${dbpass}
      DBPORT: ${dbport}

      # External Redis (DragonflyDB)
      REDIS_HOST: ${Redis_host}
      REDIS_PASSWORD: ${Redis_password}

      # Local MinIO
      MINIO_HOST: ${Minio_host}
      MINIO_USER: ${Minio_user}
      MINIO_PASSWORD: ${Minio_password}

      # Ensure your Go server binds to 0.0.0.0:8080
      PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - inner

  minio:
    image: minio/minio:latest
    command: server /export
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    volumes:
      - "./data/minio:/data:Z"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inner

  nginx:
    image: nginx:latest
    volumes:
      - "./sample-files:/usr/share/nginx/html:ro"
    ports:
      - "8081:80"
    networks:
      - inner

networks:
  inner:
    external: true
