version : "3"

services:
    app: 
        build: .
        env_file: .env
        ports:
            - 8080:8080
        depends_on:
            - "redis"
            - "postgres"
            - "minio"
        environment: 
            GIN_MODE : release
        networks:
            - inner
       
    redis :
        image : redis
        ports: 
            - 6379:6379
        networks:
            - inner
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: 1202212022AaAa
            PGDATA : /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data:Z
        networks:
                - inner
    nginx:
        image : nginx
        volumes:
            - ./sample-files:/usr/share/nginx/html:ro
        ports:
            - "8081:80"
        environment:
            - NGINX_PORT=80
        networks:
            - inner
    minio:
        image : minio/minio
        ports: 
            - "9000:9000"
        volumes: 
            -  ./data/minio:/data:Z
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        command: server /export
        environment: 
            - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
            - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        networks:
            - inner
networks:
    inner: